# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(23292A)
$foreground = rgb(ACEBC7)
$color0 = rgb(484E50)
$color1 = rgb(022128)
$color2 = rgb(022529)
$color3 = rgb(03412E)
$color4 = rgb(056133)
$color5 = rgb(126686)
$color6 = rgb(0E9447)
$color7 = rgb(81DAA7)
$color8 = rgb(5A9875)
$color9 = rgb(032C36)
$color10 = rgb(033137)
$color11 = rgb(05563D)
$color12 = rgb(068144)
$color13 = rgb(1888B2)
$color14 = rgb(13C55F)
$color15 = rgb(81DAA7)
