# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Desactivar Waybar si JaKooLit lo lanzó en otro lado (opcional pero seguro)
exec-once = pkill waybar

# Iniciar utilidades de tus dotfiles
exec-once = swaybg -i $(find ~/Pictures/Wallpapers/ -type f | shuf -n 1) # Fondo aleatorio
exec-once = nm-applet --indicator

# Iniciar Dank Material Shell (DMS)
exec-once = dms run
