# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(100F12)
$foreground = rgb(E3CED8)
$color0 = rgb(39383A)
$color1 = rgb(120D0D)
$color2 = rgb(19140F)
$color3 = rgb(432F44)
$color4 = rgb(4D2F41)
$color5 = rgb(514779)
$color6 = rgb(84576C)
$color7 = rgb(CFB1BF)
$color8 = rgb(917C86)
$color9 = rgb(181111)
$color10 = rgb(211A14)
$color11 = rgb(5A3F5B)
$color12 = rgb(663E56)
$color13 = rgb(6B5FA1)
$color14 = rgb(B07490)
$color15 = rgb(CFB1BF)
