# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(151717)
$foreground = rgb(E5F3D0)
$color0 = rgb(3B3E3E)
$color1 = rgb(4C5459)
$color2 = rgb(306229)
$color3 = rgb(5C6264)
$color4 = rgb(496C39)
$color5 = rgb(6E6E70)
$color6 = rgb(87A65B)
$color7 = rgb(D1E6B4)
$color8 = rgb(93A17E)
$color9 = rgb(667076)
$color10 = rgb(408337)
$color11 = rgb(7B8385)
$color12 = rgb(62904C)
$color13 = rgb(939395)
$color14 = rgb(B5DD7A)
$color15 = rgb(D1E6B4)
