# Variables
$iDIR = "$HOME/.config/swaync/images/ja.png"

general {
    lock_cmd = pidof hyprlock || hyprlock # runs hyprlock if it is not already running (this is always run when "loginctl lock-session" is called) 
    # unlock_cmd = killall hyprlock # kills hyprlock when unlocking (this is always run when "loginctl unlock-session" is called)
    before_sleep_cmd = loginctl lock-session    # ensures that the session is locked before going to sleep
    after_sleep_cmd = hyprctl dispatch dpms on # turn of screen after sleep (not strictly necessary, but just in case)
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
}

# 🌓 STAGE 1: Dimming (Efficiency)
# Dims the screen at 5 minutes to save power without locking you out yet
listener {
    timeout = 300                                
    on-timeout = brightnessctl set 10% -q
    on-resume = brightnessctl set 100% -q
}

# 🔔 STAGE 2: Warning
listener {
    timeout = 540                                
    on-timeout = notify-send -i $iDIR " You are idle!" 
    on-resume = notify-send -i $iDIR " Oh! you're Back" " Hello !!!"  
}

# 🔐 STAGE 3: Screenlock
listener {
    timeout = 600                                
    on-timeout = playerctl status 2>/dev/null | grep -q 'Playing' || loginctl lock-session
}

# 🌑 STAGE 4: DPMS (Monitor Standby)
# Turns off the display 30s after locking
listener {
    timeout = 630                                
    on-timeout = playerctl status 2>/dev/null | grep -q 'Playing' || hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 💤 STAGE 5: Suspend (Deep Sleep)
# After 20 minutes of inactivity, save the battery
listener {
    timeout = 1200                               
    on-timeout = playerctl status 2>/dev/null | grep -q 'Playing' || systemctl suspend               
}
