# Variables
$iDIR = "$HOME/.config/swaync/images/ja.png"

general {
    # 🛡️ THE NVIDIA PATCH: 100ms delay to let the driver wake up before rendering
    lock_cmd = sleep 0.1 && dms ipc call lock lock
    
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 🌓 STAGE 1: Dimming (Efficiency)
# Dims the screen at 5 minutes to save power without locking you out yet
listener {
    timeout = 300                                
    on-timeout = brightnessctl set 10% -q
    on-resume = brightnessctl set 100% -q
}

# 🔔 STAGE 2: Warning
listener {
    timeout = 540                                
    on-timeout = notify-send -i $iDIR " You are idle!" 
    on-resume = notify-send -i $iDIR " Oh! you're Back" " Hello !!!"  
}

# 🔐 STAGE 3: Screenlock
listener {
    timeout = 600                                
    on-timeout = loginctl lock-session           
}

# 🌑 STAGE 4: DPMS (Monitor Standby)
# Turns off the display 30s after locking
listener {
    timeout = 630                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 💤 STAGE 5: Suspend (Deep Sleep)
# After 20 minutes of inactivity, save the battery
listener {
    timeout = 1200                               
    on-timeout = systemctl suspend               
}
