-- Generated by nwg-displays on 2026-09-22 at 22:00:22. Do not edit manually.

hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x1521",
    disabled = true
})
hl.monitor({
    output = "desc:Hikom Co. Ltd. HIKVISION GT5797967",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1
})
