# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Desactivar Waybar si JaKooLit lo lanzó en otro lado (opcional pero seguro)
exec-once = pkill waybar

# dotfiles utilities
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Start Dank Material Shell (DMS)
exec-once = dms run
