# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

# -----------------------------------------------------------
# 🪟 GNOME Characters (Emoji Gestor) - FIX LATER
# -----------------------------------------------------------
# windowrule = float,org.gnome.Characters
# windowrule = center,org.gnome.Characters
# windowrule = size 600 500,org.gnome.Characters
# windowrule = pin,org.gnome.Characters
