# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E3CED8
background         #100F12
cursor             #827476

active_tab_foreground     #100F12
active_tab_background     #E3CED8
inactive_tab_foreground   #E3CED8
inactive_tab_background   #100F12

active_border_color   #E3CED8
inactive_border_color #100F12
bell_border_color     #120D0D

color0      #39383A
color1		#120D0D
color2		#19140F
color3		#432F44
color4		#4D2F41
color5		#514779
color6		#84576C
color7		#CFB1BF
color8		#917C86
color9		#181111
color10		#211A14
color11		#5A3F5B
color12		#663E56
color13		#6B5FA1
color14		#B07490
color15		#CFB1BF
