# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E5F3D0
background         #151717
cursor             #92BB84

active_tab_foreground     #151717
active_tab_background     #E5F3D0
inactive_tab_foreground   #E5F3D0
inactive_tab_background   #151717

active_border_color   #E5F3D0
inactive_border_color #151717
bell_border_color     #4C5459

color0      #3B3E3E
color1		#4C5459
color2		#306229
color3		#5C6264
color4		#496C39
color5		#6E6E70
color6		#87A65B
color7		#D1E6B4
color8		#93A17E
color9		#667076
color10		#408337
color11		#7B8385
color12		#62904C
color13		#939395
color14		#B5DD7A
color15		#D1E6B4
