bind = Super, N, exec, dms ipc call night toggle # Night Mode: Toggle
bind = Super Shift, N, exec, dms ipc call notifications toggle # Notifications: Toggle
bind = Super Shift, P, exec, dms ipc call powermenu toggle # Power Menu: Toggle
bind = Super Shift, V, exec, dms ipc call clipboard toggle # Clipboard: Toggle
